---
name: 🔒 Security Vulnerability
description: Report a security vulnerability (for sensitive issues, please email instead)
labels:
  - security
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us keep the project secure!

        **For sensitive security issues**, please consider reporting privately via email instead of using this public form.
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe do you consider this vulnerability?
      options:
        - Critical - Remote code execution, data breach
        - High - Significant security impact
        - Medium - Limited security impact
        - Low - Minimal security impact
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Affected version(s)
      description: Which version(s) of mkdocs-kroki-plugin are affected?
      placeholder: e.g., 1.0.0 or all versions
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Vulnerability description
      description: Describe the security vulnerability in detail.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can this vulnerability be reproduced or exploited?
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested fix or mitigation
      description: Do you have any suggestions on how to fix or mitigate this issue?
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Any relevant CVEs, security advisories, or related documentation?
      placeholder: "CVE-XXXX-XXXXX, links to advisories, etc."
  - type: checkboxes
    id: terms
    attributes:
      label: I read and agree to the contribution guidelines
      description: |
        By submitting this issue, you read and agree to the contribution guidelines.
      options:
        - label: I read and agree to the contribution guidelines
          required: true
